app/core/__init__.py
from flask import Blueprint

core = Blueprint('core', __name__, template_folder='templates')

from . import views

app/core/views.py
from flask import redirect, url_for, render_template, request
import dataset

from ..core import core


@core.route('/')
def index():
	return render_template("index.html")

@core.route('/discovered')
def discovered():
	db_discovered = dataset.connect("sqlite:///app/discovered.db")
	results = db_discovered.query("SELECT * FROM discovered ORDER BY occurences DESC, id DESC")
	return render_template("display.html", results=results)

@core.route('/followers/<int:occurences>')
def followers(occurences):
	db_followers = dataset.connect("sqlite:///app/database.db")
	results = db_followers['followers'].find(occurences=int(occurences))
	return render_template("display_followers.html", results=results)

@core.route('/discovered/<int:rank>')
def discovered_rank(rank):
    db_followers = dataset.connect("sqlite:///app/database.db")
    db_discovered = dataset.connect("sqlite:///app/discovered.db")

    #We get the early followers with the corresponding rank
    early_followers = set()
    follower_rows = db_followers['followers'].find(occurences=rank)
    for row in follower_rows:
        early_followers.add(row['follower_id'])

    #we get the projects followed by the early followers
    results = []
    for row in db_discovered['discovered'].find(order_by="-id"):
        occurences = 0
        #Tracks if the project is followed by at least one early follower
        flag = False
        #if the early follower's id is in the list, we add the project
        for element in row['featured_in'].split(","):
            if int(element) in early_followers:
                occurences += 1
                flag = True
        if flag:
            row['occurences'] = occurences
            results.append(row)

    return render_template("display.html", results=results)

app/core/templates/display.html
{% extends 'base.html' %}

{% block content %}
	<table>
		<tr>
			<th>id</th>
			<th>username</th>
			<th>occurences</th>
	    </tr>
		{% for result in results %}
			<tr>
				<td>
					{{result['id']}}
				</td>
				<td>
					<a href="{{ "https://twitter.com/"+result['name'] }}"> {{result['name']}} </a>
				</td>
				<td>
					{{result['occurences']}}
				</td>

			</tr>
		{% endfor %}
	</table>
{% endblock %}

app/core/templates/display_followers.html
{% extends 'base.html' %}

{% block content %}
	<table>
		<tr>
			<th>id</th>
			<th>twitter id</th>
			<th>occurences</th>
	    </tr>
		{% for result in results %}
			<tr>
				<td>
					{{result['id']}}
				</td>
				<td>
					{{result['follower_id']}}
				</td>
				<td>
					{{result['occurences']}}
				</td>

			</tr>
		{% endfor %}
	</table>
{% endblock %}

app/core/templates/index.html
{% extends 'base.html' %}

{% block style %}
<style>
	#infos
	{
		position: relative;
		top: 50%;
	    transform: translateY(-50%);
	}
</style>
{% endblock %}

{% block content %}
<div class="ui center aligned container" id="infos">
	<div class="ui grid">
  		<div class="one column row">
    		<div class="column">
				<h1 class="ui header">A simple twitter crawler</h1>
    		</div>
  		</div>
		<div class="one column row">
    		<div class="column">
				<a href="{{ url_for('core.discovered') }}">Discovered users list</a>
    		</div>
  		</div>
	</div>
</div>
{% endblock %}